### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ludohenin** [ludohenin/ng2-seed-cli#1]
Lets first discuss the roadmap and implementation details:
- [ ] Cleanup of the mess around here
- [ ] Create the forward command towards a seed project

The following (and future tasks) must be included inside angular2-seed IMO.
- [ ] Add Init task (clone and clean repo)
  - Clean Readme
  - Clean .git
  - Option to initialize a blank app ?
- [ ] Add task to update seed tools

// cc @d3viant0ne @mgechev

**Comment by joshwiens** [comment]
- [ ] Create component ( standard style-guide / css )
- [ ] Create component ( User defined / preprocessor of choice )

As for the init, it would be cool if you could define the repo it's pulling from for those that use sass, bootstrap or whatever else.

**Comment by ludohenin** [comment]
Repo or branch ... the problem I see with foreign repo is the lack of updates.
Maybe we should have some sort of .ng2seedrc for that.

**Comment by joshwiens** [comment]
Yeah, I was only suggesting it as an overridable option. An rc file should work fine for that with the default, of course being the main seed.

**Comment by ludohenin** [comment]
structure proposal from the seed
**Edit**

```
├── tools
│   ├── cli
│   │   ├── program
│   │   ├── project
│   │   │   └── templates
│   │   │   │   └── components
│   │   │   │   └── ...
│   │   ├── seed
│   │   │   └── templates
│   │   │   │   └── components
│   │   │   │   └── ...
```

Same way, project prevails over seed when same name found

**Comment by ludohenin** [comment]
One of my concern with `commander` at the moment (haven't dig enough yet) is that command have to be in `.bin` folder
```bash
$ ng2seed init # bin/ng2seed-init.js
$ ng2seed update  # bin/ng2seed-update.js
```
There might be way to tell commander to load files from another location.
